apiVersion: apps/v1
kind: Deployment
#Especificações do replicaset
metadata:
  name: portal-noticias-deployment
spec:
  #Todas as especificações do nosso POD
  template:
    metadata:
      name: portal-noticias
      labels: 
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          envFrom:
            - configMapRef:
                name: portal-configmap
  replicas: 3
  #O kubernetes pod padrão não conhece o tamplete, daí tem que especificar esse seletor
  selector:
    matchLabels:
      app: portal-noticias # igual do labels: app (linha 12)