apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-container
          name: primeiro-pv
  #Vinculado ao POD e não ao container, fica identado fora do container  
  #Definindo um PVC (persistent volume claim)  
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim: 
        #nome definido no metadata:app no arquivo pvc.yaml
        claimName: pvc-1
