apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  #Faz com que seja acessado pelo pvc.yaml
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce #Escrita de um POd por vez no volume
  #Nome do disco  do provider GCP
  gcePersistentDisk:
    pdName: pv-disk
  storageClassName: standard