apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-2
spec:
  #Faz com que acesse o pv.yaml
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce #Escrita de um POd por vez no volume
  #Faz referência ao sc.yaml metadata:app 
  storageClassName: slow